[versions]
android-plugin = "7.4.0"
compose = "1.4.0-alpha05"
compose-compiler = "1.4.0"
kotlin = "1.8.0"
ktor = "2.1.2"
kotlin-result = "1.1.16"
hilt = "2.44"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-plugin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
app-cash-sqldelight = "app.cash.sqldelight:2.0.0-alpha05"

[libraries]
desugar = "com.android.tools:desugar_jdk_libs:1.1.8"

app-cash-sqldelight-android-driver = "app.cash.sqldelight:android-driver:2.0.0-alpha05"
app-cash-sqldelight-coroutines = "app.cash.sqldelight:coroutines-extensions-jvm:2.0.0-alpha05"
app-cash-sqldelight-paging = "app.cash.sqldelight:androidx-paging3-extensions:2.0.0-alpha05"

androidx-activity = "androidx.activity:activity-compose:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-compose-material3 = "androidx.compose.material3:material3:1.0.0-beta03"
androidx-compose-material2 = "androidx.compose.material:material:1.4.0-alpha04"
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
androidx-paging-runtime = "androidx.paging:paging-runtime:3.2.0-alpha03"
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha17"
androidx-navigation = "androidx.navigation:navigation-compose:2.5.3"

coil = "io.coil-kt:coil-compose:2.2.2"

com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

jsoup = "org.jsoup:jsoup:1.15.3"

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlin-result" }

kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"

# for build-logic only
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }