[versions]
android-plugin = "7.3.1"
kotlin = "1.7.20"
compose = "1.3.0-rc01"
compose-compiler = "1.3.2"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
desugar = "com.android.tools:desugar_jdk_libs:1.1.8"

androidx-activity = "androidx.activity:activity-compose:1.6.0"
androidx-compose-material3 = "androidx.compose.material3:material3:1.0.0-beta03"
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"

ktor-client-core = "io.ktor:ktor-client-core:2.1.2"
ktor-client-android = "io.ktor:ktor-client-android:2.1.2"

kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"

# for build-logic only
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }